# Generated by Django 4.2.2 on 2025-06-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
