# Generated by Django 5.2 on 2025-05-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название заголовка", max_length=250, verbose_name="Название заголовка"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Введите текстовое описание", null=True, verbose_name="Текст"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="product/image",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "publication_attribute",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, чтобы опубликовать запись на сайте",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Автоматически увеличивается при каждом просмотре страницы.",
                        verbose_name="Количество просмотров",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Моя запись",
                "verbose_name_plural": "Мои записи",
                "ordering": ["-created_at"],
            },
        ),
    ]
