# Generated by Django 5.2 on 2025-05-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование контакта", max_length=150, verbose_name="Наименование контакта"
                    ),
                ),
                ("email", models.EmailField(help_text="Введите email", max_length=254, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Введите номер телефона", max_length=20, verbose_name="Номер телефона"
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Введите адрес", verbose_name="Адрес")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
    ]
