# Generated by Django 4.2.2 on 2025-06-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publication_attribute",
            field=models.BooleanField(
                default=False, help_text="Отметьте, чтобы опубликовать запись на сайте", verbose_name="Опубликовано"
            ),
        ),
    ]
